services:
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "5000:5000"
        depends_on:
            - web1
            - web2
        restart: always

    web1:
        build: .
        environment:
            - DATABASE_URL_1=postgres://url_shortener:5002@postgres:5432/shard_1
            - DATABASE_URL_2=postgres://url_shortener:5002@postgres:5432/shard_2
            - DATABASE_URL_3=postgres://url_shortener:5002@postgres:5432/shard_3
            - REDIS_URL=redis://redis1:6379
        depends_on:
            postgres:
                condition: service_healthy
            redis1:
                condition: service_started
        restart: always

    web2:
        build: .
        environment:
            - DATABASE_URL_1=postgres://url_shortener:5002@postgres:5432/shard_1
            - DATABASE_URL_2=postgres://url_shortener:5002@postgres:5432/shard_2
            - DATABASE_URL_3=postgres://url_shortener:5002@postgres:5432/shard_3
            - REDIS_URL=redis://redis2:6379
        depends_on:
            postgres:
                condition: service_healthy
            redis2:
                condition: service_started
        restart: always

    redis1:
        image: redis:latest
        container_name: redis-1
        ports:
            - "6380:6379"
        restart: always

    redis2:
        image: redis:latest
        container_name: redis-2
        ports:
            - "6381:6379"
        restart: always

    postgres:
        image: postgres:latest
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: url_shortener
            POSTGRES_PASSWORD: 5002
        ports:
            - "5433:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U url_shortener"]
            interval: 10s
            retries: 5
            timeout: 5s

volumes:
    pg_data:
